chatbot_token:
  token: PLACEHOLDER

models:
  base_url: "http://localhost:11434"
  logic_model: "qwen2.5:7b-instruct-q5_k_m"
  creative_model: "gemma2:9b-instruct-q5_k_m"
  free_chat_model: "llama3.1:8b-instruct-q8_0"
  embedding_model: "mxbai-embed-large"
