chatbot_token:
  token: 8384880191:AAHSjSmVu-ceiRPCckVDlfay_fEEWf6kiV8

agents:
  llm: ollama/llama3.1:8b-instruct-q8_0
  url: http://localhost:11434

chatbot:
  llm:
    name: llama3.1:8b-instruct-q8_0
    provider_name: ollama
    url: http://localhost:11434
  embedding_model:
    name: mxbai-embed-large
    provider_name: ollama
    url: http://localhost:11434
